# 问题生成--代码运行及问题汇总



### Demo代码示例：

1. 阿里云天池大数据--中药问题生成--第一名
   - https://github.com/kangyishuai/CHINESE-MEDICINE-QUESTION-GENERATION
2. 第六名
   - https://github.com/menghuanlater/Tianchi2020ChineseMedicineQuestionGeneration
3. 第四名
   - https://github.com/chenxichen95/Tianchi2020ChineseMedicineQuestionGeneration





## 代码运行问题

1、环境配置：

```shell
# tensorflow==1.14.0
pip install keras==2.3.1
pip install bert4keras
pip install rouge
pip install 'h5py==2.10.0' --force-reinstall
```

2、ckpt设置

- [参考链接1][https://github.com/tensorflow/models/issues/2676]

- 问题描述：

  model.ckpt.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?

- 解决方案：

  Apparently in V2 checkpoints, you should only include the filename up to ".ckpt". For instance if the checkpoint filename is `model.ckpt.data-00000-of-00001` then you should only use `model.ckpt`. Using the full filename leads to getting a DataLossError.

